-- All migrations in order, for pasting into the Supabase SQL editor in one go.
-- Generated from supabase/migrations/. Edit those files, not this one.

-- ================================================================ 20260928000100_schema.sql
-- Shuttle bookings: tables.
--
-- A job is one trip: a pickup on a date and time, from A to B, for a customer.
-- Dates and times are stored as local wall-clock values (date + time, no time
-- zone) because the business runs in one place and a 5:30 am airport run is
-- 5:30 am whatever the server's clock says. settings.timezone is only used to
-- work out what "today" is.
--
-- Money lives in its own table (job_money) so drivers can read their jobs
-- without ever being able to read prices, costs or profit.

create schema if not exists app;

create type public.app_role as enum ('owner', 'dispatcher', 'driver');
create type public.job_status as enum ('enquiry', 'confirmed', 'completed', 'cancelled', 'no_show');

-- ---------------------------------------------------------------- settings (one row)

create table public.settings (
  id            smallint primary key default 1 check (id = 1),
  business_name text not null default 'Shuttle Bookings' check (length(business_name) between 1 and 80),
  currency      text not null default 'NZD' check (currency ~ '^[A-Z]{3}$'),
  timezone      text not null default 'Pacific/Auckland' check (length(timezone) between 3 and 64),
  updated_at    timestamptz not null default now()
);
insert into public.settings (id) values (1);

-- ---------------------------------------------------------------- people

create table public.profiles (
  user_id      uuid primary key references auth.users (id) on delete cascade,
  display_name text not null check (length(btrim(display_name)) between 1 and 80),
  email        text not null,
  phone        text check (length(phone) <= 40),
  role         public.app_role not null default 'driver',
  -- calendar colour, e.g. #2563eb
  colour       text not null default '#1d4ed8' check (colour ~ '^#[0-9a-fA-F]{6}$'),
  -- what the business pays this person per hour; used to suggest a job's driver cost
  pay_rate     numeric(8, 2) check (pay_rate >= 0),
  is_active    boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- ---------------------------------------------------------------- vehicles

create table public.vehicles (
  id           uuid primary key default gen_random_uuid(),
  name         text not null unique check (length(btrim(name)) between 1 and 60),
  registration text check (length(registration) <= 20),
  seats        smallint check (seats between 1 and 99),
  -- running cost per km (fuel, tyres, servicing); used to suggest a job's fuel cost
  cost_per_km  numeric(6, 3) check (cost_per_km >= 0),
  notes        text check (length(notes) <= 500),
  is_active    boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- ---------------------------------------------------------------- jobs

create table public.jobs (
  id              uuid primary key default gen_random_uuid(),
  job_no          bigint generated by default as identity (start with 1001) unique,
  status          public.job_status not null default 'confirmed',
  service_type    text not null default 'airport'
                  check (service_type in ('airport', 'corporate', 'event', 'tour', 'school', 'charter', 'other')),
  pickup_date     date not null,
  pickup_time     time not null,
  duration_min    integer not null default 60 check (duration_min between 5 and 1440),
  pickup_address  text not null check (length(btrim(pickup_address)) between 1 and 200),
  dropoff_address text not null check (length(btrim(dropoff_address)) between 1 and 200),
  passengers      smallint not null default 1 check (passengers between 1 and 99),
  luggage         smallint not null default 0 check (luggage between 0 and 199),
  flight_no       text check (length(flight_no) <= 20),
  customer_name   text not null check (length(btrim(customer_name)) between 1 and 120),
  customer_phone  text check (length(customer_phone) <= 40),
  customer_email  text check (length(customer_email) <= 120),
  booking_source  text not null default 'phone'
                  check (booking_source in ('phone', 'email', 'website', 'walk_in', 'repeat', 'agent', 'other')),
  driver_id       uuid references public.profiles (user_id) on delete set null,
  vehicle_id      uuid references public.vehicles (id) on delete set null,
  notes           text check (length(notes) <= 1000),
  driver_notes    text check (length(driver_notes) <= 1000),
  distance_km     numeric(7, 1) check (distance_km >= 0),
  created_by      uuid default auth.uid() references public.profiles (user_id) on delete set null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  completed_at    timestamptz
);

create index jobs_pickup_idx on public.jobs (pickup_date, pickup_time);
create index jobs_driver_idx on public.jobs (driver_id, pickup_date);
create index jobs_status_idx on public.jobs (status, pickup_date);

-- The money side of a job. Office only.
create table public.job_money (
  job_id         uuid primary key references public.jobs (id) on delete cascade,
  price          numeric(10, 2) not null default 0 check (price >= 0),
  driver_cost    numeric(10, 2) not null default 0 check (driver_cost >= 0),
  fuel_cost      numeric(10, 2) not null default 0 check (fuel_cost >= 0),
  tolls_parking  numeric(10, 2) not null default 0 check (tolls_parking >= 0),
  other_cost     numeric(10, 2) not null default 0 check (other_cost >= 0),
  payment_status text not null default 'unpaid' check (payment_status in ('unpaid', 'paid', 'invoiced')),
  updated_at     timestamptz not null default now()
);

-- ---------------------------------------------------------------- time off

create table public.time_off (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references public.profiles (user_id) on delete cascade,
  starts_on  date not null,
  ends_on    date not null,
  note       text check (length(note) <= 200),
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  check (ends_on >= starts_on),
  check (ends_on - starts_on <= 366)
);

create index time_off_range_idx on public.time_off (starts_on, ends_on);

-- ================================================================ 20260928000200_security.sql
-- Roles and row-level security.
--
-- owner      : everything, including team, vehicles and settings.
-- dispatcher : office staff. All jobs, money, calendar, dashboard, vehicles.
-- driver     : their own jobs and their own time off. Never sees money.
--
-- All of it is enforced here; the app only decides what to show.

-- ---------------------------------------------------------------- helpers
-- SECURITY DEFINER so policies can read profiles without recursing into the
-- profiles policies. A deactivated person resolves to no role at all.

create or replace function app.current_role()
returns public.app_role
language sql stable security definer set search_path = ''
as $$
  select p.role from public.profiles p
  where p.user_id = auth.uid() and p.is_active
$$;

create or replace function app.is_active()
returns boolean language sql stable security definer set search_path = ''
as $$ select app.current_role() is not null $$;

create or replace function app.is_office()
returns boolean language sql stable security definer set search_path = ''
as $$ select coalesce(app.current_role() in ('owner', 'dispatcher'), false) $$;

create or replace function app.is_owner()
returns boolean language sql stable security definer set search_path = ''
as $$ select coalesce(app.current_role() = 'owner', false) $$;

grant usage on schema app to authenticated;
revoke all on all functions in schema app from public, anon;
grant execute on all functions in schema app to authenticated;

-- ---------------------------------------------------------------- triggers

create or replace function app.touch_updated_at()
returns trigger language plpgsql set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end $$;

create trigger touch before update on public.settings  for each row execute function app.touch_updated_at();
create trigger touch before update on public.profiles  for each row execute function app.touch_updated_at();
create trigger touch before update on public.vehicles  for each row execute function app.touch_updated_at();
create trigger touch before update on public.jobs      for each row execute function app.touch_updated_at();
create trigger touch before update on public.job_money for each row execute function app.touch_updated_at();

-- completed_at follows the status.
create or replace function app.stamp_completed()
returns trigger language plpgsql set search_path = ''
as $$
begin
  if new.status = 'completed' then
    if tg_op = 'INSERT' or old.status is distinct from 'completed' then
      new.completed_at := now();
    end if;
  else
    new.completed_at := null;
  end if;
  return new;
end $$;

create trigger stamp_completed before insert or update of status on public.jobs
  for each row execute function app.stamp_completed();

-- Every new auth user gets a profile. The very first one is the owner (the
-- person setting the system up); everyone after that starts as a driver and
-- the owner changes their role. Public sign-ups stay off in Supabase, so the
-- only way in is an invite from the owner.
create or replace function app.handle_new_user()
returns trigger language plpgsql security definer set search_path = ''
as $$
declare
  palette text[] := array['#1d4ed8', '#15803d', '#be185d', '#c2410c', '#6d28d9', '#0e7490', '#a16207', '#b91c1c', '#4338ca', '#047857'];
  n integer;
begin
  select count(*) into n from public.profiles;
  insert into public.profiles (user_id, display_name, email, role, colour)
  values (
    new.id,
    coalesce(nullif(btrim(new.raw_user_meta_data ->> 'display_name'), ''), split_part(new.email, '@', 1)),
    new.email,
    case when exists (select 1 from public.profiles where role = 'owner') then 'driver' else 'owner' end::public.app_role,
    palette[1 + n % array_length(palette, 1)]
  )
  on conflict (user_id) do nothing;
  return new;
end $$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function app.handle_new_user();

-- There must always be at least one active owner, or nobody could manage the team.
create or replace function app.keep_an_owner()
returns trigger language plpgsql security definer set search_path = ''
as $$
begin
  if not exists (select 1 from public.profiles where role = 'owner' and is_active) then
    raise exception 'There must always be at least one active owner.' using errcode = 'check_violation';
  end if;
  return null;
end $$;

create constraint trigger keep_an_owner after update or delete on public.profiles
  deferrable initially deferred
  for each row execute function app.keep_an_owner();

-- ---------------------------------------------------------------- grants
-- Nothing is reachable without a login.

revoke all on all tables in schema public from anon;
grant select, insert, update, delete on all tables in schema public to authenticated;

-- ---------------------------------------------------------------- RLS

alter table public.settings  enable row level security;
alter table public.profiles  enable row level security;
alter table public.vehicles  enable row level security;
alter table public.jobs      enable row level security;
alter table public.job_money enable row level security;
alter table public.time_off  enable row level security;

-- settings: everyone signed in reads (business name, time zone); owner edits.
create policy settings_read  on public.settings for select to authenticated using (app.is_active());
create policy settings_owner on public.settings for update to authenticated using (app.is_owner()) with check (app.is_owner());

-- profiles: you see yourself; the office sees the team; only the owner changes anyone.
-- Profiles are created by the auth trigger, never inserted directly.
create policy profiles_read  on public.profiles for select to authenticated
  using (user_id = auth.uid() or app.is_office());
create policy profiles_owner on public.profiles for update to authenticated
  using (app.is_owner()) with check (app.is_owner());

-- vehicles: everyone signed in reads (drivers see which vehicle they're in); the office manages.
create policy vehicles_read   on public.vehicles for select to authenticated using (app.is_active());
create policy vehicles_office on public.vehicles for all    to authenticated using (app.is_office()) with check (app.is_office());

-- jobs: the office does everything; a driver reads only the jobs assigned to
-- them. Drivers change their jobs only through public.driver_update_job.
create policy jobs_office      on public.jobs for all    to authenticated using (app.is_office()) with check (app.is_office());
create policy jobs_driver_read on public.jobs for select to authenticated
  using (driver_id = auth.uid() and app.is_active());

-- money: office only.
create policy money_office on public.job_money for all to authenticated using (app.is_office()) with check (app.is_office());

-- time off: your own, or anyone's if you're in the office.
create policy time_off_read on public.time_off for select to authenticated
  using ((user_id = auth.uid() and app.is_active()) or app.is_office());
create policy time_off_write on public.time_off for all to authenticated
  using ((user_id = auth.uid() and app.is_active()) or app.is_office())
  with check ((user_id = auth.uid() and app.is_active()) or app.is_office());

-- ================================================================ 20260928000300_job_functions.sql
-- Writes that must happen in one go, or that drivers are allowed to make.

-- The office saves a job and its money together, in one transaction.
-- SECURITY INVOKER: the caller's row-level security still applies, so a
-- driver calling this gets nowhere. p_id null = new job.
create or replace function public.save_job(p_id uuid, p_job jsonb, p_money jsonb)
returns uuid
language plpgsql security invoker set search_path = ''
as $$
declare
  j public.jobs := jsonb_populate_record(null::public.jobs, p_job);
  m public.job_money := jsonb_populate_record(null::public.job_money, coalesce(p_money, '{}'::jsonb));
  v_id uuid;
begin
  if not app.is_office() then
    raise exception 'Only the owner or office staff can create or edit jobs.' using errcode = 'insufficient_privilege';
  end if;

  if p_id is null then
    insert into public.jobs (
      status, service_type, pickup_date, pickup_time, duration_min, pickup_address, dropoff_address,
      passengers, luggage, flight_no, customer_name, customer_phone, customer_email, booking_source,
      driver_id, vehicle_id, notes, distance_km
    ) values (
      coalesce(j.status, 'confirmed'), coalesce(j.service_type, 'airport'), j.pickup_date, j.pickup_time,
      coalesce(j.duration_min, 60), j.pickup_address, j.dropoff_address, coalesce(j.passengers, 1),
      coalesce(j.luggage, 0), j.flight_no, j.customer_name, j.customer_phone, j.customer_email,
      coalesce(j.booking_source, 'phone'), j.driver_id, j.vehicle_id, j.notes, j.distance_km
    )
    returning id into v_id;
  else
    update public.jobs set
      status = coalesce(j.status, status), service_type = coalesce(j.service_type, service_type),
      pickup_date = j.pickup_date, pickup_time = j.pickup_time, duration_min = coalesce(j.duration_min, duration_min),
      pickup_address = j.pickup_address, dropoff_address = j.dropoff_address,
      passengers = coalesce(j.passengers, passengers), luggage = coalesce(j.luggage, luggage), flight_no = j.flight_no,
      customer_name = j.customer_name, customer_phone = j.customer_phone, customer_email = j.customer_email,
      booking_source = coalesce(j.booking_source, booking_source), driver_id = j.driver_id, vehicle_id = j.vehicle_id,
      notes = j.notes, distance_km = j.distance_km
    where id = p_id
    returning id into v_id;
    if v_id is null then
      raise exception 'That job no longer exists.' using errcode = 'no_data_found';
    end if;
  end if;

  if p_money is not null then
    insert into public.job_money (job_id, price, driver_cost, fuel_cost, tolls_parking, other_cost, payment_status)
    values (
      v_id, coalesce(m.price, 0), coalesce(m.driver_cost, 0), coalesce(m.fuel_cost, 0),
      coalesce(m.tolls_parking, 0), coalesce(m.other_cost, 0), coalesce(m.payment_status, 'unpaid')
    )
    on conflict (job_id) do update set
      price = excluded.price, driver_cost = excluded.driver_cost, fuel_cost = excluded.fuel_cost,
      tolls_parking = excluded.tolls_parking, other_cost = excluded.other_cost,
      payment_status = excluded.payment_status;
  end if;

  return v_id;
end $$;

-- A driver marks one of their own jobs done (or no-show, or back to
-- confirmed if they tapped the wrong button), with notes and the distance
-- driven. Nothing else about the job can be changed this way.
create or replace function public.driver_update_job(
  p_job_id uuid,
  p_status public.job_status,
  p_driver_notes text,
  p_distance_km numeric
)
returns void
language plpgsql security definer set search_path = ''
as $$
declare
  j public.jobs;
begin
  select * into j from public.jobs where id = p_job_id for update;
  if j.id is null or j.driver_id is distinct from auth.uid() or not app.is_active() then
    raise exception 'That job isn''t assigned to you.' using errcode = 'insufficient_privilege';
  end if;
  if p_status not in ('confirmed', 'completed', 'no_show') then
    raise exception 'Drivers can mark a job done or no-show, nothing else.' using errcode = 'check_violation';
  end if;
  if j.status not in ('confirmed', 'completed', 'no_show') then
    raise exception 'This job is %, so only the office can change it.', j.status using errcode = 'check_violation';
  end if;
  if p_distance_km is not null and (p_distance_km < 0 or p_distance_km > 5000) then
    raise exception 'Distance must be between 0 and 5000 km.' using errcode = 'check_violation';
  end if;

  update public.jobs set
    status = p_status,
    driver_notes = nullif(btrim(coalesce(p_driver_notes, '')), ''),
    distance_km = coalesce(p_distance_km, distance_km)
  where id = p_job_id;
end $$;

revoke all on function public.save_job(uuid, jsonb, jsonb) from public, anon;
revoke all on function public.driver_update_job(uuid, public.job_status, text, numeric) from public, anon;
grant execute on function public.save_job(uuid, jsonb, jsonb) to authenticated;
grant execute on function public.driver_update_job(uuid, public.job_status, text, numeric) to authenticated;
