-- Shuttle bookings: tables.
--
-- A job is one trip: a pickup on a date and time, from A to B, for a customer.
-- Dates and times are stored as local wall-clock values (date + time, no time
-- zone) because the business runs in one place and a 5:30 am airport run is
-- 5:30 am whatever the server's clock says. settings.timezone is only used to
-- work out what "today" is.
--
-- Money lives in its own table (job_money) so drivers can read their jobs
-- without ever being able to read prices, costs or profit.

create schema if not exists app;

create type public.app_role as enum ('owner', 'dispatcher', 'driver');
create type public.job_status as enum ('enquiry', 'confirmed', 'completed', 'cancelled', 'no_show');

-- ---------------------------------------------------------------- settings (one row)

create table public.settings (
  id            smallint primary key default 1 check (id = 1),
  business_name text not null default 'Shuttle Bookings' check (length(business_name) between 1 and 80),
  currency      text not null default 'NZD' check (currency ~ '^[A-Z]{3}$'),
  timezone      text not null default 'Pacific/Auckland' check (length(timezone) between 3 and 64),
  updated_at    timestamptz not null default now()
);
insert into public.settings (id) values (1);

-- ---------------------------------------------------------------- people

create table public.profiles (
  user_id      uuid primary key references auth.users (id) on delete cascade,
  display_name text not null check (length(btrim(display_name)) between 1 and 80),
  email        text not null,
  phone        text check (length(phone) <= 40),
  role         public.app_role not null default 'driver',
  -- calendar colour, e.g. #2563eb
  colour       text not null default '#1d4ed8' check (colour ~ '^#[0-9a-fA-F]{6}$'),
  -- what the business pays this person per hour; used to suggest a job's driver cost
  pay_rate     numeric(8, 2) check (pay_rate >= 0),
  is_active    boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- ---------------------------------------------------------------- vehicles

create table public.vehicles (
  id           uuid primary key default gen_random_uuid(),
  name         text not null unique check (length(btrim(name)) between 1 and 60),
  registration text check (length(registration) <= 20),
  seats        smallint check (seats between 1 and 99),
  -- running cost per km (fuel, tyres, servicing); used to suggest a job's fuel cost
  cost_per_km  numeric(6, 3) check (cost_per_km >= 0),
  notes        text check (length(notes) <= 500),
  is_active    boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- ---------------------------------------------------------------- jobs
--
-- One row per booking, like one row of the monthly booking sheet.
-- Money follows the sheet: Charge − Driver pay = the business's pay.
-- Driver pay and the amount a driver must collect on the day live on the job
-- itself, because the assigned driver is allowed to see both. Everything else
-- about money (the charge, expenses, payment records) is in job_money.

create table public.jobs (
  id              uuid primary key default gen_random_uuid(),
  job_no          bigint generated by default as identity (start with 1001) unique,
  -- the business's own reference (TW-20260910-024), or blank
  booking_ref     text check (length(booking_ref) <= 60),
  status          public.job_status not null default 'confirmed',
  service_type    text not null default 'airport'
                  check (service_type in ('airport', 'cruise', 'tour', 'transfer', 'event', 'corporate', 'school', 'charter', 'other')),
  pickup_date     date not null,
  pickup_time     time not null,
  -- how long the driver is tied up, including driving back; blocks their calendar
  duration_min    integer not null default 240 check (duration_min between 5 and 1440),
  pickup_address  text not null check (length(btrim(pickup_address)) between 1 and 300),
  dropoff_address text not null check (length(btrim(dropoff_address)) between 1 and 300),
  passengers      smallint not null default 1 check (passengers between 1 and 99),
  luggage         smallint not null default 0 check (luggage between 0 and 199),
  flight_no       text check (length(flight_no) <= 60),
  customer_name   text not null check (length(btrim(customer_name)) between 1 and 120),
  customer_phone  text check (length(customer_phone) <= 60),
  customer_email  text check (length(customer_email) <= 120),
  booking_source  text not null default 'phone'
                  check (booking_source in ('phone', 'text', 'whatsapp', 'messenger', 'email', 'website', 'repeat', 'agent', 'walk_in', 'other')),
  driver_id       uuid references public.profiles (user_id) on delete set null,
  vehicle_id      uuid references public.vehicles (id) on delete set null,
  -- the other leg of a there-and-back booking
  linked_job_id   uuid references public.jobs (id) on delete set null,
  -- one trip carrying several bookings: shared jobs may overlap for a driver
  is_shared       boolean not null default false,
  driver_pay      numeric(10, 2) not null default 0 check (driver_pay >= 0),
  -- what the driver collects from the customer on the day (0 if prepaid)
  collect_amount  numeric(10, 2) not null default 0 check (collect_amount >= 0),
  -- how the driver says they collected it
  collected_via   text check (collected_via in ('cash', 'card', 'online', 'bank')),
  notes           text check (length(notes) <= 1000),
  driver_notes    text check (length(driver_notes) <= 1000),
  distance_km     numeric(7, 1) check (distance_km >= 0),
  created_by      uuid default auth.uid() references public.profiles (user_id) on delete set null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  completed_at    timestamptz
);

create index jobs_pickup_idx on public.jobs (pickup_date, pickup_time);
create index jobs_driver_idx on public.jobs (driver_id, pickup_date);
create index jobs_status_idx on public.jobs (status, pickup_date);
create index jobs_ref_idx on public.jobs (booking_ref);

-- The money side of a job. Office only.
create table public.job_money (
  job_id         uuid primary key references public.jobs (id) on delete cascade,
  price          numeric(10, 2) not null default 0 check (price >= 0),
  -- optional running costs on top of driver pay
  fuel_cost      numeric(10, 2) not null default 0 check (fuel_cost >= 0),
  tolls_parking  numeric(10, 2) not null default 0 check (tolls_parking >= 0),
  other_cost     numeric(10, 2) not null default 0 check (other_cost >= 0),
  payment_status text not null default 'unpaid' check (payment_status in ('unpaid', 'pay_on_day', 'invoiced', 'paid')),
  payment_method text check (payment_method in ('online', 'cash', 'card', 'bank')),
  paid_on        date,
  updated_at     timestamptz not null default now()
);

-- ---------------------------------------------------------------- time off

create table public.time_off (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references public.profiles (user_id) on delete cascade,
  starts_on  date not null,
  ends_on    date not null,
  note       text check (length(note) <= 200),
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  check (ends_on >= starts_on),
  check (ends_on - starts_on <= 366)
);

create index time_off_range_idx on public.time_off (starts_on, ends_on);
